name : First Woekflow

on:
  push: 
    branches:
       -main:
jobs:
   example-job:
      runs-on: ubuntu-latest

      steps:
        - name: print a welcome message
          run : echo "welcome to our cicd "
